services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    command: npm run dev 

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OUTSCRAPER_API_KEY=${OUTSCRAPER_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      # Add other environment variables as needed

  redis:
    image: "redis:7.4.0"
    ports:
      - "6379:6379"

  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: tests
    depends_on:
      - redis
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OUTSCRAPER_API_KEY=${OUTSCRAPER_API_KEY}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      # Add other environment variables as needed
    command: ["python", "-m", "unittest", "discover", "-s", "tests"]
