services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
      - frontend_node_modules:/frontend/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres  
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OUTSCRAPER_API_KEY=${OUTSCRAPER_API_KEY}

      
    networks:
      - app-network

  redis:
    image: "redis:7.4.0"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network
  
  postgres: 
    image: postgres:latest  
    container_name: my_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}      
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB} 
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    networks:
      - app-network

volumes:
  frontend_node_modules:
  postgres_data:  

networks:
  app-network:
    driver: bridge
